### ISSUE TITLE
发布的模型，无法解压。  

### ISSUE THREAD

**Issue by yuanzhenjie** [chen-judge/SKT#1]
`(base) [root@dl-gpu trained_model]# tar   -xf   partA_student.pth.tar
tar: 它似乎不像是一个 tar 归档文件
tar: 跳转到下一个头
tar: 由于前次错误，将以上次的错误状态退出`

请问是否百度云盘中的model是否可以用来验证

**Comment by yuanzhenjie** [comment]
MD5 (partA_student.pth.tar) = 880a0aa77bb18fe109e9f8e428f77a53

**Comment by yuanzhenjie** [comment]
MD5 (partA_student.pth.tar) = 880a0aa77bb18fe109e9f8e428f77a53

**Comment by yuanzhenjie** [comment]
MD5 (partA_student.pth.tar) = 880a0aa77bb18fe109e9f8e428f77a53

**Comment by yuanzhenjie** [comment]
MD5 (partA_student.pth.tar) = 880a0aa77bb18fe109e9f8e428f77a53

**Comment by yuanzhenjie** [comment]
MD5 (partA_student.pth.tar) = 880a0aa77bb18fe109e9f8e428f77a53

**Comment by yuanzhenjie** [comment]
MD5 (partA_student.pth.tar) = 880a0aa77bb18fe109e9f8e428f77a53

**Comment by yuanzhenjie** [comment]
MD5 (partA_student.pth.tar) = 880a0aa77bb18fe109e9f8e428f77a53

**Comment by yuanzhenjie** [comment]
MD5 (partA_student.pth.tar) = 880a0aa77bb18fe109e9f8e428f77a53

**Comment by yuanzhenjie** [comment]
MD5 (partA_student.pth.tar) = 880a0aa77bb18fe109e9f8e428f77a53

**Comment by chen-judge** [comment]
直接 torch.load('partA_student.pth.tar') 即可

**Comment by yuanzhenjie** [comment]
谢谢了，如题主描述。
本地工程检查出了环境问题。
