### ISSUE TITLE
sh test,sh无法运行

### ISSUE THREAD

**Issue by xuguozhi** [chen-judge/SKT#2]
No such file or directory: 'A_test.json'

**Comment by xuguozhi** [comment]
no checkpoint found at '/models/CSRNet_models/partA_student.pth.tar'

**Comment by yuanzhenjie** [comment]
'A_test.json 文件应该是手动制作下(从UCF-QNRF_ECCV18挑选几张组成)吧.......
可以参考make_json.py

**Comment by yuanzhenjie** [comment]
'A_test.json 文件应该是手动制作下(从UCF-QNRF_ECCV18挑选几张组成)吧.......

**Comment by chen-judge** [comment]
请读取你的路径与模型文件

**Comment by yuanzhenjie** [comment]
可以test 的
<img width="691" alt="图片" src="https://user-images.githubusercontent.com/5775576/91316967-07f4c000-e7ec-11ea-9a15-0417afe5440c.png">
应该需要将路径配置的改成本地路径
