### ISSUE TITLE
是不是只能在shanghai测试集上测试？

### ISSUE THREAD

**Issue by xuguozhi** [chen-judge/SKT#3]
这个project可不可以测试单张图像？还是只能跑固定的数据集？

**Comment by yuanzhenjie** [comment]
论文主 基于torch.utils.data.DataLoader 组成测试数据集，便于训练与验证。
1.可以把单张组装在dataloader。（浪费资源...）
2.就得参看工程的生产密度图与统计的代码。（类似在reid 工程的Feature extraction提取代码，在进行 与目标的sim比对）

**Comment by chen-judge** [comment]
你可以自己简单写一个单张的。参照代码对数据进行预处理，并读入模型进行inference
