### ISSUE TITLE
Where can i find the 1/4-BL + SKT network？I only find the CSRNet in models module

### ISSUE THREAD

**Issue by Goolo2** [chen-judge/SKT#5]
Dear author,

I have gained a lot from your paper, and I appreciate your pioneering work. But I can't find the definition of the BL teacher network and the BL student network in your code. I only find the CSRNet in the folder models. May you tell me some detail about it? I am eager to do further research on the basis of your work.

Thank you very much!

**Comment by jaaaaaaaake** [comment]
您好，我遇到了同样的问题，请问您解决了吗。

**Comment by jaaaaaaaake** [comment]
> Dear author,
> 
> I have gained a lot from your paper, and I appreciate your pioneering work. But I can't find the definition of the BL teacher network and the BL student network in your code. I only find the CSRNet in the folder models. May you tell me some detail about it? I am eager to do further research on the basis of your work.
> 
> Thank you very much!

您好，我遇到了同样的问题，请问您解决了吗？

**Comment by liulingbo918** [comment]
The BL  teacher and student  model have been released at [https://drive.google.com/drive/folders/17oxen8sNHtumcFL8hu9Z0Owuc6dWD8zV](url)



- [ ]

**Comment by liulingbo918** [comment]
> > Dear author,
> > I have gained a lot from your paper, and I appreciate your pioneering work. But I can't find the definition of the BL teacher network and the BL student network in your code. I only find the CSRNet in the folder models. May you tell me some detail about it? I am eager to do further research on the basis of your work.
> > Thank you very much!
> 
> 您好，我遇到了同样的问题，请问您解决了吗？

The BL  teacher and student  model have been released at [https://drive.google.com/drive/folders/17oxen8sNHtumcFL8hu9Z0Owuc6dWD8zV](url)

**Comment by jaaaaaaaake** [comment]
> > > Dear author,
> > > I have gained a lot from your paper, and I appreciate your pioneering work. But I can't find the definition of the BL teacher network and the BL student network in your code. I only find the CSRNet in the folder models. May you tell me some detail about it? I am eager to do further research on the basis of your work.
> > > Thank you very much!
> > 
> > 
> > 您好，我遇到了同样的问题，请问您解决了吗？
> 
> The BL teacher and student model have been released at [https://drive.google.com/drive/folders/17oxen8sNHtumcFL8hu9Z0Owuc6dWD8zV](url)

Thank you for your reply.But these in Google Drive seem to be some sort of pre-training model. What we need is the code of BL tracher and 1/4BL student network,which we can train on our dataset. could you provide it for us?Thanks very much.Looking forward to your reply!
